
include: package:flutter_lints/flutter.yaml

analyzer:
  enable-experiment:
    - records
    - patterns
  plugins:
    - custom_lint
  exclude:
    - lib/**.g.dart
    - lib/**.freezed.dart

custom_lint:
  rules:
    - missing_provider_scope: false

linter:
  rules:
    prefer_single_quotes: true
