name: riverpod_playground
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  device_preview: ^1.1.0
  device_preview_screenshot: ^1.0.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.0
  flutter_markdown: ^0.6.17+1
  freezed_annotation: ^2.4.1
  go_router: ^10.0.0
  hooks_riverpod: ^2.3.8
  logger_plus:
    git: https://github.com/refectco/logger_plus
  riverpod_annotation: ^2.1.2
  riverpod_lint: ^2.0.1
  syntax_highlight: ^0.2.0

dev_dependencies:
  build_runner: ^2.4.6
  custom_lint: ^0.5.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.2
  riverpod_generator: ^2.2.6

flutter:
  uses-material-design: true

  assets:
    - assets/markdown/